### ISSUE TITLE
OLM flake tracking

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-lifecycle-manager#2401]
- [ ] "Subscription creation if not installed"
- [ ] "Installing bundles with new object types when a bundle with a pdb, priorityclass, and VPA object is installed should create the additional bundle objects"
- [ ] "Subscription when an entry in the middle of a channel does not provide a required GVK should create a Subscription for the latest entry providing the required GVK
- [ ] "ClusterServiceVersion when a csv exists specifying two replicas with one max unavailable remains in phase Succeeded when only one pod is available"
- [ ] "Subscription can reconcile InstallPlan status"
- [x] "Install Plan creation with pre existing CRD owners PreExistingCRDOwnerIsReplaced"
- [ ] "Install Plan when an InstallPlan is created with no valid OperatorGroup present should clear clear up the condition in the InstallPlan status that contains an error message when a valid OperatorGroup is created"
- [x] "Subscription with starting CSV"
- [ ] "CSVs with a Webhook when Installed from a catalog Source Validating, Mutating and Conversion webhooks work as intended"
- [x] "ClusterServiceVersion emits CSV requirement events"
- [ ] "Operator Group cleanup csvs with bad owner operator groups expand_less"
- [ ] "Catalog represents a store of bundles which OLM can use to install Operators adding catalog template adjusts image used"
- [ ] "Garbage collection for dependent resources when a bundle with configmap and secret objects is installed when the CSV is deleted OLM should have removed the old configmap and put the new configmap in place"
- [ ] "Garbage collection for dependent resources when a bundle with configmap and secret objects is installed when the CSV is deleted OLM should delete the associated configmap and secret"
- [ ] "Subscription creation with dependencies required and provided in different versions of an operator in the same package"
- [ ] "CRD Versions allows a CRD upgrade that doesn't cause data loss"

**Comment by timflannagan** [comment]
Misc: seeing quite a bit of connection-refused logs in the catalog-operator when firing off ListBundles calls:
```
E1006 17:13:09.466730       1 queueinformer_operator.go:290] sync "operators" failed: [error using catalog test-catalog (in namespace operators): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.96.133.46:50051: connect: connection refused", error using catalog operatorhubio-catalog (in namespace operator-lifecycle-manager): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.96.33.109:50051: connect: connection refused"]
```

**Comment by akihikokuroda** [comment]
As of today (01/21/2022), I see the following e2e failures.  

- should have copied CSVs in all other Namespaces
- should create a Subscription for the latest entry providing the required GVK 
- delete internal registry pod triggers recreation
- can satisfy an associated ClusterServiceVersion's ownership requirement
- should surface components in its status

In addition to these, I see some failures that are caused by the installplan creation wait timeout.   They have the following  in the test log.
```
waiting for catalog pod scoped-catsrc-hzt42 to be available (for sync) - TRANSIENT_FAILURE
catalog scoped-catsrc-hzt42 pod with address scoped-catsrc-hzt42.scoped-ns-cfw9r.svc:50051
03:47:22.1316:  (): nil
waiting for scoped-sub-wz8bw to have installplan ref
03:47:23.131:  (): nil
waiting for scoped-sub-wz8bw to have installplan ref
03:47:24.1319:  (): nil
waiting for scoped-sub-wz8bw to have installplan ref
03:47:25.1315:  (): nil
waiting for scoped-sub-wz8bw to have installplan ref

.........

waiting for scoped-sub-wz8bw to have installplan ref
03:52:21.1343: never got correct status: v1alpha1.SubscriptionStatus{CurrentCSV:"", InstalledCSV:"", Install:(*v1alpha1.InstallPlanReference)(nil), State:"", Reason:"", InstallPlanGeneration:0, InstallPlanRef:(*v1.ObjectReference)(nil), CatalogHealth:
```
I'll open issues for them later.
